### ISSUE TITLE
Peer review - Code

### ISSUE THREAD

**Issue by veerleprins** [lisaoude/Gifinder#18]
## Feedback
- No idea if your code is structured according to your diagrams as they are not yet in your readme. 😞 
- It is better to put your script tag in your body at the bottom. Because you give the reason that you have to wait for the html elements. But you load your html elements with JavaScript. 😄  
- In your main.js you have a comment: 'this function shows the trending gifs'. But I think the 'start' function does not specifically show the trending gifs but rather invokes your router. 😉 
- You now have an index.js file within your modules views folder that you don't use. I think you can remove these. 😄
- Do you only have 1 component called gifs.js?  
- Are your views, config and components just modules? 
- I wonder if you understand all your code correctly yourself... 🤯 

## To Solve This Issue:

- [x] Add **script tag** to **bottom of body tag** in HTML.
- [x] **Add comments** that **make sense** for your code. 
- [x] **Remove** your **index.js** file within your modules views folder.
- [x] Try to take a look at what modules are, what components are and how your code actually works.

**Comment by lisaoude** [comment]
Script tag for js files will remain in head, because it defers by default.

**Comment by lisaoude** [comment]
I have taken a look at what modules actually are and what components are. I have changed my folders and file structure accordingly. I don't have a components file at this moment, because the code that would go in that folder in their respectative files, are currently still in another function. This wil be split up in to smaller pieces of code and moved to my components folder.
